# ---------------------------------
# API Server 配置
[Server]
ServicePort         = 8087
MonitorPort         = 8089
GracefulTimeOutMs   = 10000


# ---------------------------------
# 日志相关配置
[Loggers.access]
LogName     = "access"
LogLevel    = "INFO"
RotateWhen  = "MIDNIGHT"
BackupCount = 1
Format      = "[%D %T] [%L] [%S] %M"
StdOut      = false

[Loggers.sql]
LogName     = "sql"
LogLevel    = "INFO"
RotateWhen  = "MIDNIGHT"
BackupCount = 1
Format      = "[%D %T] %M"
StdOut      = false

[Loggers.gslb]
LogName     = "gslb"
LogLevel    = "INFO"
RotateWhen  = "MIDNIGHT"
BackupCount = 1
Format      = "[%D %T] [%L] [%S] %M"
StdOut      = false


# ---------------------------------
# 数据库相关配置
# see https://github.com/go-sql-driver/mysql/blob/master/dsn.go#L37
[Databases.bfe_db]
DBName              = "bfe_api_190"
Addr                = "10.130.29.32:5535"
Net                 = "tcp"
User                = "blb"
Passwd              = "blb"
MultiStatements     = true
MaxAllowedPacket    = 67108864
ParseTime           = true
AllowNativePasswords= true
Params 				= {"loc"="Local", timeout="1s", "readTimeout"="10s", "writeTimeout"="10s"}

Driver              = "mysql"
MaxOpenConns        = 100
MaxIdleConns        = 100
ConnMaxIdleTimeMs   = 50000
ConnMaxLifetimeMs   = 50000


# ---------------------------------
# Auth20 配置，鉴权相关
[Auth20]
ClientID        = "ILB_ARG_API_SERVER_AUTH2_CLIENT_ID"
ClientSecret    = "ILB_ARG_API_SERVER_AUTH2_CLIENT_SECRET"
TokenURL        = "ILB_ARG_API_SERVER_AUTH2_SERVER/token"
# 如果不希望程序自动调整第三方登录，将本配置置空
LoginPage       = "ILB_ARG_API_SERVER_AUTH2_SERVER/authorize"
RedirectURI     = "ILB_ARG_API_SERVER_AUTH2_REDIRECT_URL"
JWKRSAPublicKey = """{
	"kty": "RSA",
	"e": "AQAB",
	"kid": "rsa1",
	"alg": "RS256",
	"n": "qt6yOiI_wCoCVlGO0MySsez0VkSqhPvDl3rfabOslx35mYEO-n4ABfIT5Gn2zN-CeIcOZ5ugAXvIIRWv5H55-tzjFazi5IKkOIMCiz5__MtsdxKCqGlZu2zt-BLpqTOAPiflNPpM3RUAlxKAhnYEqNha6-allPnFQupnW_eTYoyuzuedT7dSp90ry0ZcQDimntXWeaSbrYKCj9Rr9W1jn2uTowUuXaScKXTCjAmJVnsD75JNzQfa8DweklTyWQF-Y5Ky039I0VIu-0CIGhXY48GAFe2EFb8VpNhf07DP63p138RWQ1d3KPEM9mYJVpQC68j3wzDQYSljpLf9by7TGw"
}"""


# ---------------------------------
# 依赖系统相关配置
[Depends]
LokiServerAddr          = "http://localhost:3100"
GetInstanceByServiceCMD = "get_instance_by_service"
NavTreeFile             = "${conf_dir}/nav_tree.toml"
I18nDir     			= "${conf_dir}/i18n"
NLBVsConfFileDeprecated = "${conf_dir}/bgw_vs.conf"
NLBVsConfFile           = "${conf_dir}/virtual_server.conf"
Grafana                 = "http://bjyz-op-bfedev00.bjyz.baidu.com:8300/"
UIIcon                  = ""
UILogo                  = ""


# ---------------------------------
# TLS默认配置
[TLSGlobal]
DefaultNextProtos       = ["http/1.1"]
DefaultChacha20         = false
DefaultClientCAName     = "ca-bundle"
DefaultSecurityGrade    = "B"


# ---------------------------------
# Runtime Config
[RunTime]
# you can use "Skip {role_name} as authorization header to access api server if open this optional
# eg: Headers[Authorization] = "Skip admin"
# don't open it on production environment
SkipTokenValidate   = true
# sql will be record to log file when this option be opend
RecordSQL           = true
# how long use must login again
SessionExpireDay    = 10
# static file path, when dynamic router not be matched, static file will be return if found
StaticFilePath      = "../static"
# debug info will be add to response when this option be opend
Debug               = false
AccessLogWithRspBodyExcludePaths = ["^/inner-api/v1/configs/gslb$", "auth/op-logs$"]
